### ISSUE TITLE
Can´t add another character

### ISSUE THREAD

**Issue by hilocz** [uplink42/etmv2#128]
I registered into ETM and added one API key, when I go to API Key Management I don´t see the character in the list, when I try add another character I´m getting this error >

```
ERROR - 2017-04-17 13:36:18 --> Severity: error --> Exception: Return value of ValidateRequest::checkCharacterBelong() must be of the type boolean, none returned /pub/www/htdocs/etm/application/models/common/ValidateRequest.php 39
Query error: Cannot add or update a child row: a foreign key constraint fails (`trader`.`aggr`, CONSTRAINT `fk_aggr_user1` FOREIGN KEY (`user_iduser`) REFERENCES `user` (`iduser`)) - Invalid query: INSERT INTO `aggr` (`idaggr`, `user_iduser`, `character_eve_idcharacter`) VALUES (NULL, 0, 1425027272)
```

**Comment by hilocz** [comment]
Even after update from latest master getting same error.

**Comment by uplink42** [comment]
I have tried to recreate the latest master branch on my local machine following the current schema and seeders.  Everything works fine. What id does your current user have? Perhaps this is because you've created your user with a previous (outdated) db schema.

**Comment by hilocz** [comment]
```
select * from aggr;
+--------+-------------+---------------------------+
| idaggr | user_iduser | character_eve_idcharacter |
+--------+-------------+---------------------------+
|      1 |           1 |                  92299669 |
|      8 |           2 |                  92571238 |
+--------+-------------+---------------------------+
2 rows in set (0.00 sec)
```
When I look on API Management I don´t see any character.

**Comment by uplink42** [comment]
Try pressing 'logoff', login again and try to add a new character.

Also, place this log entry  at the beginning of the `Apikeymanagement `controller/`addCharactersStep `method and tell me what it says on the error log.

```
public function addCharactersStep(int $apikey, string $vcode, string $char1 = null, string $char2 = null, string $char3 = null)
    {
        log_message('error', $this->user_id); // add this log entry
```

**Comment by hilocz** [comment]
```
ERROR - 2017-04-18 20:55:25 --> Severity: error --> Exception: Argument 1 passed to Dashboard::index() must be of the type integer, string given, called in /srv/www/htdocs/etm/system/core/Codeigniter.php on line 514 /srv/www/htdocs/etm/application/controllers/Dashboard.php 21
ERROR - 2017-04-18 20:55:28 --> Severity: error --> Exception: Return value of ValidateRequest::checkCharacterBelong() must be of the type boolean, none returned /srv/www/htdocs/etm/application/models/common/ValidateRequest.php 39
ERROR - 2017-04-18 20:56:17 --> 0
ERROR - 2017-04-18 20:56:17 --> Query error: Cannot add or update a child row: a foreign key constraint fails (`trader`.`aggr`, CONSTRAINT `fk_aggr_user1` FOREIGN KEY (`user_iduser`) REFERENCES `user` (`iduser`)) - Invalid query: INSERT INTO `aggr` (`idaggr`, `user_iduser`, `character_eve_idcharacter`) VALUES (NULL, 0, 1425027272)
```
Doesn´t look, that there is something new logged.

**Comment by uplink42** [comment]
It definetly has something to do with your user account (says the id is 0). Maybe it was not properly created. Try deleting all entries from the aggr table and create a new user with the same characters and try adding a new one again.

**Comment by hilocz** [comment]
I truncated table aggr and ETM asked about API, after I added a character I got error 404 and in URL was this >

`v2/main/login/logout`

After new login , the imported user was there, but on API Management page I don´t see this character and can´t remove it.

**Comment by hilocz** [comment]
I suspect, that there can be a problem with session management, because I´m getting very often disconnected and need to relogin.

**Comment by uplink42** [comment]
I have fixed the wrong redirect on the latest `master` branch.

Yes it's most likely an issue with sessions on your account. What version of php are you using?

**Comment by hilocz** [comment]
PHP is 7.1 , I have on same server another project, there is no problem with sessions, is there way to check it ?

This is current setup 

```
session
Session Support 	enabled
Registered save handlers 	files user redis rediscluster
Registered serializer handlers 	php_serialize php php_binary
Directive	Local Value	Master Value
session.auto_start	Off	Off
session.cache_expire	180	180
session.cache_limiter	nocache	nocache
session.cookie_domain	no value	no value
session.cookie_httponly	Off	Off
session.cookie_lifetime	0	0
session.cookie_path	/	/
session.cookie_secure	Off	Off
session.gc_divisor	1000	1000
session.gc_maxlifetime	1440	1440
session.gc_probability	1	1
session.lazy_write	On	On
session.name	PHPSESSID	PHPSESSID
session.referer_check	no value	no value
session.save_handler	files	files
session.save_path	/tmp	/tmp
session.serialize_handler	php	php
session.sid_bits_per_character	5	5
session.sid_length	26	26
session.upload_progress.cleanup	On	On
session.upload_progress.enabled	On	On
session.upload_progress.freq	1%	1%
session.upload_progress.min_freq	1	1
session.upload_progress.name	PHP_SESSION_UPLOAD_PROGRESS	PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix	upload_progress_	upload_progress_
session.use_cookies	On	On
session.use_only_cookies	On	On
session.use_strict_mode	Off	Off
session.use_trans_sid	0	0
```

**Comment by hilocz** [comment]
Tested if session starts with 

```
session_start();
if (session_status() == PHP_SESSION_ACTIVE) {
  echo 'Session is active';};
```

and works.

**Comment by uplink42** [comment]
I will try a different approach with the session class, though it's strange that I've never had issues on my windows machine before.

**Comment by hilocz** [comment]
Did install from scratch and the errors are still there 

```
ERROR - 2017-04-21 09:57:57 --> Severity: error --> Exception: Argument 1 passed to StockLists::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Stocklists.php 19
ERROR - 2017-04-21 09:57:58 --> Severity: error --> Exception: Argument 1 passed to TradeRoutes::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Traderoutes.php 20
ERROR - 2017-04-21 10:04:03 --> Severity: error --> Exception: Argument 1 passed to CitadelTax::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Citadeltax.php 31
ERROR - 2017-04-21 10:04:06 --> Severity: error --> Exception: Argument 1 passed to Settings::index() must be of the type integer, string given, called in /pub/www/htdocs/etm/system/core/CodeIgniter.php on line 514 /pub/www/htdocs/etm/application/controllers/Settings.php 42
ERROR - 2017-04-21 10:04:15 --> Severity: error --> Exception: Return value of ValidateRequest::checkCharacterBelong() must be of the type boolean, none returned /pub/www/htdocs/etm/application/models/common/ValidateRequest.php 39
```

For example on API Management page I don´t see any character to be removed. Page is blank.

**Comment by uplink42** [comment]
I've removed the type hinting from url parameters in the `dev `branch, try updating and see if it solves your issue.

Other than that I'm really out of ideas here

**Comment by uplink42** [comment]
I have deployed the 2.21 update to my server and found no issues. Let me know if it works for you now.

**Comment by hilocz** [comment]
Still same problem, same errors in log file. Maybe enable some debug logging will help ?  

I looked , where is PHP saving session files and there are many files like 

etm_sessioned5124c4f3eca5d97f1b5724ceffef78vmikfiitnl1ce417h6ot5dcjtm0ip0tb

but from April 17
today they look like this 

sess_lv69krmuihlld7uh9cp6cp19is

**Comment by uplink42** [comment]
Just to be sure, what does your browser URL look like when this error
occurs?

**Comment by hilocz** [comment]
When I´m on Api Management page ...

https://pathfinder.bandofmagnus.cz:8443/apikeymanagement/index/1425027272?aggr=

I can post, what is in session file too.

**Comment by uplink42** [comment]
The session files look different because I changed the mechanism a while ago, I think the different looking files are normal. Also, I have created a testing account just to see what the issue is on your server.

**Comment by hilocz** [comment]
I created session test PHP script

```
<?php
//simple counter to test sessions. should increment on each page reload.
session_start();
$count = isset($_SESSION['count']) ? $_SESSION['count'] : 1;

echo $count;

$_SESSION['count'] = ++$count;
?>
```

and is working, every reload increased showed number.

**Comment by uplink42** [comment]
Maybe try adding a `session_start()` at the beginning of the root `index.php` file. It's not optimal but may fix it for your environment

**Comment by hilocz** [comment]
Tried that, but it doesn´t helped. 
I put that session test code in index.php and without session_start() the count doesn´t incresed. It was staying on 1. 

The pathfinder.bandofmagnus.cz is CNAME, I will test it on A record.

**Comment by hilocz** [comment]
Tested on A record, same behavior, tested on plain port 443, even disabled Pathfinder config on NginX.
